apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: job1
        image: redis-job:v1
        command: ["python",  "job.py"]
      restartPolicy: Never
  backoffLimit: 1
