apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbitmq-master
    namespace: rabbitmq
    labels:
      app: broker
spec:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  replicas: 1
  rabbitmq:
    additionalConfig: |
      default_user = guest
      default_pass = guest
