apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbitmq-master
    namespace: rabbitmq
    labels:
      app: broker
spec:
  replicas: 1
  rabbitmq:
    additionalConfig: |
      default_user = guest
      default_pass = guest
