apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: redis-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: dns
        image: redis-worker:v1
        name: redis-worker
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
status: {}
