apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: rabbitmq-worker
  namespace: rabbitmq
spec:
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - env:
        - name: RABBITMQ_HOST
          value: rabbitmq-master
        - name: PYTHONUNBUFFERED
          value: '1'
        - name: HostMQ
        image: rabbitmq-worker:v1
        name: rabbitmq-worker
        resources:
          requests:
            cpu: 60m
          limits:
            cpu: 60m
